{{/*
#  ============LICENSE_START=======================================================
#   Copyright (C) 2023 Nordix Foundation. All rights reserved.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: RELEASE
    heritage: Helm
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: RELEASE
    spec:
      initContainers:
      - command:
        - sh
        args:
        - -c
        - "cd /config-input && for PFILE in `ls -1`; do envsubst <${PFILE} >/config/${PFILE}; done"
        env:
        - name: RESTSERVER_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-restserver-creds
              key: login
        - name: RESTSERVER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}-restserver-creds
              key: password

        volumeMounts:
        - mountPath: /config-input
          name: apexconfig-input
        - mountPath: /config
          name: apexconfig
        image: docker.io/dibi/envsubst:1
        imagePullPolicy: {{ .Values.global.pullPolicy | default .Values.pullPolicy }}
        name: {{ .Chart.Name }}-update-config
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.repository }}/{{ .Values.global.image.apex }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh","-c"]
          args: ["/opt/app/policy/apex-pdp/bin/apexOnapPf.sh -c /home/apexuser/config/OnapPfConfig.json"]
          ports:
          - containerPort: {{ .Values.service.externalPort }}
          {{- if eq .Values.liveness.enabled true }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          env:
          - name: REPLICAS
            value: "{{ .Values.replicaCount }}"
          volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true
          - mountPath: /var/log/onap
            name: policy-logs
          - mountPath: /home/apexuser/config
            name: apexconfig
          resources:
{{ toYaml .Values.resources.small | indent 12 }}
        {{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
        {{- end -}}
        {{- if .Values.affinity }}
        affinity:
{{ toYaml .Values.affinity | indent 10 }}
        {{- end }}
        - name: {{ .Chart.Name }}-sg
          image: {{ .Values.global.repository }}/{{ .Values.global.image.apex }}
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command: ["sh","-c"]
          args: ["/opt/app/policy/apex-pdp/bin/apexOnapPf.sh -c /home/apexuser/config/OnapPfConfigSampleGroup.json"]
          ports:
          - containerPort: {{ .Values.service.externalPortSvc2 }}
          {{- if eq .Values.liveness.enabled true }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.externalPort }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
          env:
          - name: REPLICAS
            value: "{{ .Values.replicaCount }}"
          volumeMounts:
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true
          - mountPath: /var/log/onap
            name: policy-logs
          - mountPath: /home/apexuser/config
            name: apexconfig
          resources:
{{ toYaml .Values.resources.small | indent 12 }}
        {{- if .Values.nodeSelector }}
        nodeSelector:
{{ toYaml .Values.nodeSelector | indent 10 }}
        {{- end -}}
        {{- if .Values.affinity }}
        affinity:
{{ toYaml .Values.affinity | indent 10 }}
        {{- end }}
      serviceAccountName: {{ .Chart.Name }}-read
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: policy-logs
          emptyDir: {}
        - name: apexconfig-input
          configMap:
            name: {{ .Chart.Name }}-configmap
            defaultMode: 0755
        - name: apexconfig
          emptyDir:
            medium: Memory
      imagePullSecrets:
      - name: "default-docker-registry-key"
