
apiVersion: v1
kind: ConfigMap
metadata:
 name: {{ include "policy-models-simulator.fullname" . }}-configmap
 labels:
  app: {{ include "policy-models-simulator.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  heritage: {{ .Release.Service }}
data:
{{ tpl (.Files.Glob "resources/config/*.{json,xml}").AsConfig . | indent 2 }}
{{ tpl (.Files.Glob "resources/cds/*.{json,xml}").AsConfig . | indent 2 }}
