apiVersion: v1
kind: Service
metadata:
  name: message-router
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort2 }}
      targetPort: {{ .Values.service.internalPort2 }}
      name: {{ .Values.service.portName }}2
    - port: {{ .Values.service.externalPort3 }}
      targetPort: {{ .Values.service.internalPort3 }}
      name: {{ .Values.service.portName }}3
    - port: {{ .Values.service.externalPort4 }}
      targetPort: {{ .Values.service.internalPort4 }}
      name: {{ .Values.service.portName }}4
    - port: {{ .Values.service.externalPort5 }}
      targetPort: {{ .Values.service.internalPort5 }}
      name: {{ .Values.service.portName }}5
    - port: {{ .Values.service.externalPort6 }}
      targetPort: {{ .Values.service.internalPort6 }}
      name: {{ .Values.service.portName }}6
    - port: {{ .Values.service.externalPort7 }}
      targetPort: {{ .Values.service.internalPort7 }}
      name: {{ .Values.service.portName }}7
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
