apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      name: {{ .Values.service.portName }}
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.simulators.aai.name }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.simulators.aai.externalPort }}
      targetPort: {{ .Values.service.simulators.aai.internalPort }}
      name: {{ .Values.service.simulators.aai.name }}
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.simulators.sdnc.name }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.simulators.sdnc.externalPort }}
      targetPort: {{ .Values.service.simulators.sdnc.internalPort }}
      name: {{ .Values.service.simulators.sdnc.name }}
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.simulators.so.name }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.simulators.so.externalPort }}
      targetPort: {{ .Values.service.simulators.so.internalPort }}
      name: {{ .Values.service.simulators.so.name }}
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.simulators.grpc.name }}
  labels:
{{ include "policy-models-simulator.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.service.simulators.grpc.externalPort }}
      targetPort: {{ .Values.service.simulators.grpc.internalPort }}
      name: {{ .Values.service.simulators.grpc.name }}
  selector:
    app.kubernetes.io/name: {{ include "policy-models-simulator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
