{
 "title": "Policy Drools-PDP",
 "description": "Grafana Dashboard for Policy Drools-PDP",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Quick Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Uptime (days)",
     "type": "stat",
     "description": "Uptime per pod for Policy Drools-PDP application calculated in days",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(time() - process_start_time_seconds{job=\"drools-pdp-metrics\"}) / 86400",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "description": "Policy Drools-PDP CPU Usage Monitoring",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"drools-pdp-metrics\"}[5m])*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "description": "Policy Drools-PDP Memory Usage Monitoring",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"drools-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"drools-pdp-metrics\"}",
       "legendFormat": "Heap : {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Policy Drools-PDP CPU Usage Monitoring",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"drools-pdp-metrics\"}[5m])*100",
       "legendFormat": "system: {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Policy Drools-PDP Memory Usage Monitoring",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"drools-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"drools-pdp-metrics\"}",
       "legendFormat": "Heap : {{ pod }}"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "description": "Policy Drools-PDP JVM Threads",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"drools-pdp-metrics\"}",
       "legendFormat": "Live Threads: {{ pod }}"
      },
      {
       "expr": "jvm_threads_peak{job=\"drools-pdp-metrics\"}",
       "legendFormat": "Peak Threads: {{ pod }}"
      },
      {
       "expr": "jvm_threads_daemon{job=\"policy-drools-pdp\"}",
       "legendFormat": "Daemon Threads: {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection",
     "type": "timeseries",
     "description": "GC operations per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"drools-pdp-metrics\"}[5m])",
       "legendFormat": "{{ gc }} : {{ pod }}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "description": "Average GC Time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"drools-pdp-metrics\"}[5m])/rate(jvm_gc_collection_seconds_count{job=\"drools-pdp-metrics\"}[5m])",
       "legendFormat": "avg {{ gc }} : {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Policy Deployments Total",
     "type": "bargauge",
     "description": "Policy Deployments Total for Drools-PDP",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-pdp-metrics\", operation=\"deploy\", status=\"SUCCESS\"})",
       "legendFormat": "Deploy - Success"
      },
      {
       "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-pdp-metrics\", operation=\"deploy\", status=\"FAILURE\"})",
       "legendFormat": "Deploy - Failure"
      },
      {
       "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-pdp-metrics\", operation=\"undeploy\", status=\"SUCCESS\"})",
       "legendFormat": "Undeploy - Success"
      },
      {
       "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-pdp-metrics\", operation=\"undeploy\", status=\"FAILURE\"})",
       "legendFormat": "Undeploy - Failure"
      }
     ]
    },
    {
     "title": "Policy Executions",
     "type": "bargauge",
     "description": "Policy Executions Total for Drools-PDP per instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pdpd_policy_executions_latency_seconds_count{job=\"drools-pdp-metrics\"}",
       "legendFormat": "Executions - Count"
      },
      {
       "expr": "pdpd_policy_executions_latency_seconds_sum{job=\"drools-pdp-metrics\"}",
       "legendFormat": "Executions - Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Logging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logback Total",
     "type": "stat",
     "description": "Policy number of log entries for Drool-PDP",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "logback_appender_total{job=\"drools-pdp-metrics\"}",
       "legendFormat": "Level"
      }
     ]
    }
   ]
  }
 ]
}