{
 "title": "Policy Distribution",
 "description": "Grafana Dashboard for Policy Distribution",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime (days)",
   "type": "stat",
   "description": "Uptime per pod for Policy Distribution application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"distribution-metrics\"} / 86400"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy Distribution CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"distribution-metrics\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy Distribution Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(pod)(jvm_memory_bytes_used{area=\"heap\", job=\"distribution-metrics\"}) / sum by(pod)(jvm_memory_bytes_max{area=\"heap\", job=\"distribution-metrics\"})",
     "legendFormat": "Heap : {{ pod }}"
    },
    {
     "expr": "100 * sum by(pod)(jvm_memory_bytes_used{area=\"nonheap\", job=\"distribution-metrics\"}) / sum by(pod)(jvm_memory_bytes_max{area=\"nonheap\", job=\"distribution-metrics\"})",
     "legendFormat": "Non Heap : {{ pod }}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Policy Distribution CPU Usage Monitoring",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "process_cpu_seconds_total{job=\"distribution-metrics\"} * 100",
       "legendFormat": "system: {{pod}}"
      },
      {
       "expr": "process_cpu_seconds_total{job=\"distribution-metrics\"} * 100",
       "legendFormat": "process: {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Policy Distribution Memory Usage Monitoring",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "100 * sum(jvm_memory_bytes_used{area=\"heap\", job=\"distribution-metrics\"}) / sum(jvm_memory_bytes_max{area=\"heap\", job=\"distribution-metrics\"})",
       "legendFormat": "Heap"
      },
      {
       "expr": "100 * sum(jvm_memory_bytes_used{area=\"nonheap\", job=\"distribution-metrics\"}) / sum(jvm_memory_bytes_max{area=\"nonheap\", job=\"distribution-metrics\"})",
       "legendFormat": "Non Heap"
      }
     ]
    },
    {
     "title": "JVM threads",
     "type": "timeseries",
     "description": "Policy Distribution JVM Threads",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"distribution-metrics\"}",
       "legendFormat": "Live Threads: {{ pod }}"
      },
      {
       "expr": "jvm_threads_peak{job=\"distribution-metrics\"}",
       "legendFormat": "Peak Threads: {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collection",
     "type": "timeseries",
     "description": "GC operations per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_count{job=\"distribution-metrics\"}[1h])",
       "legendFormat": "{{action}} ({{cause}}) : {{ pod }}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "description": "Average GC Time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=\"distribution-metrics\"}[1h])/rate(jvm_gc_collection_seconds_count{job=\"distribution-metrics\"}[1h])",
       "legendFormat": "avg {{action}} ({{cause}}) : {{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Distribution Statistics",
   "type": "bargauge",
   "description": "Stats for Distribution Statistics Count",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_distribution_received_count{job=\"distribution-metrics\"})",
     "legendFormat": "Total Count"
    },
    {
     "expr": "sum(distribution_success_count{job=\"distribution-metrics\"})",
     "legendFormat": "Success Count"
    },
    {
     "expr": "sum(distribution_failure_count{job=\"distribution-metrics\"})",
     "legendFormat": "Failure Count"
    },
    {
     "expr": "sum(total_download_received_count{job=\"distribution-metrics\"})",
     "legendFormat": "Total Download Count"
    },
    {
     "expr": "sum(download_success_count{job=\"distribution-metrics\"})",
     "legendFormat": "Download Success Count"
    },
    {
     "expr": "sum(download_failure_count{job=\"distribution-metrics\"})",
     "legendFormat": "Download Failure Count"
    }
   ]
  }
 ]
}