version: '2'
services:
   mariadb:
      image: mariadb:10.0.34
      container_name: mariadb
      hostname: mariadb
      command: ['--lower-case-table-names=1']
      volumes:
         - ./config/db:/docker-entrypoint-initdb.d
      expose:
       - 3306
   nexus:
      image: onap/policy/policy-nexus
      container_name: nexus
      hostname: nexus
   pap:
      image: onap/policy/policy-pe
      environment:
       - PRELOAD_POLICIES=${PRELOAD_POLICIES}
      container_name: pap
      depends_on: 
       - mariadb
      hostname: pap
      expose:
       - 8443
       - 9091
      command: pap
      volumes:
       - ./config/pe:/tmp/policy-install/config
   pdp:
      image: onap/policy/policy-pe
      container_name: pdp
      depends_on: 
       - pap
      hostname: pdp
      expose:
       - 8081
      command: pdp
      volumes:
       - ./config/pe:/tmp/policy-install/config
   brmsgw:
      image: onap/policy/policy-pe
      container_name: brmsgw
      depends_on: 
       - pap
      hostname: brmsgw
      command: brmsgw
      volumes:
       - ./config/pe:/tmp/policy-install/config
   drools:
      image: onap/policy/policy-drools
      container_name: drools
      depends_on: 
       - mariadb
       - nexus
      hostname: drools
      expose:
       - 6969
       - 9696
      volumes:
       - ./config/drools:/tmp/policy-install/config
