{{/*
# Copyright © 2022 Nordix Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - port: 3306
      targetPort: tcp-mysql
      protocol: TCP
      name: tcp-mysql
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  sessionAffinity: None

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless
  namespace: default
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - port: 4567
      targetPort: tcp-galera
      protocol: TCP
      name: tcp-galera
    - port: 4568
      targetPort: tcp-ist
      protocol: TCP
      name: tcp-ist
    - port: 4444
      targetPort: tcp-sst
      protocol: TCP
      name: tcp-sst
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  sessionAffinity: None
