Vagrant.require_version ">= 1.8.6"
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 4096]
    vb.customize ["modifyvm", :id, "--cpus", 4]
    vb.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
  end

  config.vm.define "policy" do |config|
    config.vm.hostname = "policy"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.provision "shell", path: "setup_policy.sh", privileged: false
  end

end
