#
# ===========LICENSE_START====================================================
#  Copyright (C) 2023 Nordix Foundation.
# ============================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=====================================================
#

# global config
global:
  scrape_interval: 60s
  evaluation_interval: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# scrape config
scrape_configs:
  - job_name: "api-metrics"
    metrics_path: /policy/api/v1/metrics
    static_configs:
      - targets: ["policy-api:6969"]
    basic_auth:
      username: "policyadmin"
      password: "zb!XztG34"

  - job_name: "pap-metrics"
    metrics_path: /policy/pap/v1/metrics
    static_configs:
      - targets: ["policy-pap:6969"]
    basic_auth:
      username: "policyadmin"
      password: "zb!XztG34"

  - job_name: "apex-pdp-metrics"
    static_configs:
      - targets:
          - "policy-apex-pdp:6969"
    basic_auth:
      username: "policyadmin"
      password: "zb!XztG34"

  # - job_name: "drools-apps-metrics"
  #   static_configs:
  #     - targets:
  #         - "drools-apps:9696"
  #   basic_auth:
  #     username: "demo@people.osaaf.org"
  #     password: "demo123456!"

  - job_name: "drools-pdp-metrics"
    static_configs:
      - targets:
          - "policy-drools-pdp:9696"
    basic_auth:
      username: "demo@people.osaaf.org"
      password: "demo123456!"

  - job_name: "distribution-metrics"
    static_configs:
      - targets:
          - "policy-distribution:6969"
    basic_auth:
      username: "policyadmin"
      password: "zb!XztG34"

  - job_name: "xacml-pdp-metrics"
    static_configs:
      - targets:
          - "policy-xacml-pdp:6969"
    basic_auth:
      username: "policyadmin"
      password: "zb!XztG34"

  - job_name: "acm-metrics"
    metrics_path: "/onap/policy/clamp/acm/prometheus"
    static_configs:
      - targets:
          - "policy-clamp-runtime-acm:6969"
    basic_auth:
      username: "runtimeUser"
      password: "zb!XztG34"

  - job_name: "acm-participant-policy-metrics"
    metrics_path: "/onap/policyparticipant/prometheus"
    static_configs:
      - targets:
          - "policy-clamp-ac-pf-ppnt:6969"
    basic_auth:
      username: "participantUser"
      password: "zb!XztG34"

  - job_name: "acm-participant-http-metrics"
    metrics_path: "/onap/httpparticipant/prometheus"
    static_configs:
      - targets:
          - "policy-clamp-ac-http-ppnt:8084"
    basic_auth:
      username: "participantUser"
      password: "zb!XztG34"

  - job_name: "acm-participant-k8s-metrics"
    metrics_path: "/onap/k8sparticipant/prometheus"
    static_configs:
      - targets:
          - "policy-clamp-ac-k8s-ppnt:8083"
    basic_auth:
      username: "participantUser"
      password: "zb!XztG34"
