#  ============LICENSE_START=======================================================
#   Copyright (C) 2023-2024 Nordix Foundation. All rights reserved.

#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================

#################################################################
# Global configuration defaults.
#################################################################
global:
  nodePortPrefix: 302
  aafEnabled: false
  persistence: {}

#################################################################
# Application configuration defaults.
#################################################################
# application image
pullPolicy: Always

# flag to enable debugging - application support required
debugEnabled: false

# application configuration

restServer:
  user: policyadmin
  password: zb!XztG34


# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

# probe configuration parameters
liveness:
  initialDelaySeconds: 20
  periodSeconds: 10
  # necessary to disable liveness probe when setting breakpoints
  # in debugger so K8s doesn't restart unresponsive container
  enabled: true

readiness:
  initialDelaySeconds: 20
  periodSeconds: 10

service:
  type: ClusterIP
  name: policy-apex-pdp
  portName: http
  externalPort: 6969
  externalPortSvc2: 6970
  internalPort: 6969
  nodePort: 37

jerseyServer:
  enabled: true
  portName: jersey-rest
  externalPort: 23324
  internalPort: 23324

ingress:
  enabled: false

# Resource Limit flavor -By Default using small
# Segregation for Different environment (Small and Large)
flavor: small
resources:
  small:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 1Gi
  unlimited: {}


#Pods Service Account
serviceAccount:
  nameOverride: policy-apex-pdp
  roles:
    - read
