spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
      org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
participant:
  pdpGroup: defaultGroup
  pdpType: apex
  policyApiParameters:
    clientName: api
    hostname: policy-api
    port: 6969
    userName: policyadmin
    password: zb!XztG34
    useHttps: false
    allowSelfSignedCerts: true
  policyPapParameters:
    clientName: pap
    hostname: policy-pap
    port: 6969
    userName: policyadmin
    password: zb!XztG34
    useHttps: false
    allowSelfSignedCerts: true
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: org.onap.PM_Policy
      version: 1.0.0
    participantType:
      name: org.onap.policy.clamp.acm.PolicyParticipant
      version: 2.3.1
    clampAutomationCompositionTopics:
      topicSources:
        -
          topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
          useHttps: false
      topicSinks:
        -
          topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          useHttps: false
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
server:
  port: 6969
  ssl:
    enabled: false
  servlet:
    context-path: /onap/policy/clamp/acm/policyparticipant
