{
 "title": "Policy XACML-PDP",
 "description": "Grafana Dashboard for Policy XACML-PDP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quick Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "Uptime per pod for Policy XACML-PDP application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"xacml-pdp-metrics\"})",
     "legendFormat": "process_uptime: {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy XACML-PDP CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"xacml-pdp-metrics\"}[$__range])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy XACML-PDP Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"xacml-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Heap : {{ pod }}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy XACML-PDP CPU Usage Monitoring",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"xacml-pdp-metrics\"}[$__range])*100",
     "legendFormat": "system: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy XACML-PDP Memory Usage Monitoring",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (jvm_memory_bytes_used{area=\"heap\", job=\"xacml-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"xacml-pdp-metrics\"})",
     "legendFormat": "Heap : {{ pod }}"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy XACML-PDP JVM Threads",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_daemon{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Daemon Threads: {{ pod }}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"xacml-pdp-metrics\"}[$__range])",
     "legendFormat": "{{ gc }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"xacml-pdp-metrics\"}[$__range])/rate(jvm_gc_collection_seconds_count{job=\"xacml-pdp-metrics\"}[$__range])",
     "legendFormat": "avg {{ gc }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Deployments Total",
   "type": "bargauge",
   "description": "Policy Deployments Total for XACML-PDP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job)(pdpx_policy_deployments_total{job=\"xacml-pdp-metrics\", operation=\"deploy\", status=\"SUCCESS\"})",
     "legendFormat": "{{ deploy }}"
    },
    {
     "expr": "avg by(job)(pdpx_policy_deployments_total{job=\"xacml-pdp-metrics\", operation=\"deploy\", status=\"FAILURE\"})",
     "legendFormat": "{{ deploy }}"
    },
    {
     "expr": "avg by(job)(pdpx_policy_deployments_total{job=\"xacml-pdp-metrics\", operation=\"undeploy\", status=\"SUCCESS\"})",
     "legendFormat": "{{ undeploy }}"
    },
    {
     "expr": "avg by(job)(pdpx_policy_deployments_total{job=\"xacml-pdp-metrics\", operation=\"undeploy\", status=\"FAILURE\"})",
     "legendFormat": "{{ undeploy }}"
    }
   ]
  },
  {
   "title": "Policy Decisions",
   "type": "bargauge",
   "description": "Policy Decisions Total for XACML-PDP per instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpx_policy_decisions_total{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Deny"
    },
    {
     "expr": "pdpx_policy_decisions_total{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Indeterminant"
    },
    {
     "expr": "pdpx_policy_decisions_total{job=\"xacml-pdp-metrics\"}",
     "legendFormat": "Not Applicable"
    }
   ]
  }
 ]
}