{
 "title": "Policy OPA-PDP",
 "description": "Grafana Dashboard for Policy OPA-PDP",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quick Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "Uptime per pod for Policy OPA-PDP application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"opa-pdp-metrics\"})",
     "legendFormat": "process_uptime: {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy OPA-PDP CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"opa-pdp-metrics\"}[$__range]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy OPA-PDP Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * process_resident_memory_bytes{job=\"opa-pdp-metrics\"} / (1024 * 1024 * 1024)",
     "legendFormat": "RSS : {{ pod }}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy OPA-PDP CPU Usage Monitoring",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"opa-pdp-metrics\"}[$__range])*100",
     "legendFormat": "opa: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy OPA-PDP Memory Usage Monitoring",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * process_resident_memory_bytes{job=\"opa-pdp-metrics\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Alloc : {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Decisions",
   "type": "bargauge",
   "description": "Policy Decisions Total for OPA-PDP per instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opa_decision_response_time_seconds_count{instance=\"policy-opa-pdp:8282\", job=\"opa-pdp-metrics\"}",
     "legendFormat": "Decision Count"
    }
   ]
  }
 ]
}