{
 "title": "Policy PAP Jakarta",
 "description": "Grafana Dashboard for Policy PAP",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime (days)",
   "type": "stat",
   "description": "Uptime per pod for Policy PAP application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"pap-metrics\"} / 86400",
     "legendFormat": "process_uptime: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy PAP CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"pap-metrics\"} * 100",
     "legendFormat": "system: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy PAP Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by(pod)(jvm_memory_used_bytes{area=\"heap\",job=\"pap-metrics\"}) / sum by(pod)(jvm_memory_max_bytes{area=\"heap\",job=\"pap-metrics\"})",
     "legendFormat": "Heap : {{ pod }}"
    },
    {
     "expr": "100 * sum by(pod)(jvm_memory_used_bytes{area=\"nonheap\",job=\"pap-metrics\"}) / sum by(pod)(jvm_memory_max_bytes{area=\"nonheap\",job=\"pap-metrics\"})",
     "legendFormat": "Non Heap : {{ pod }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy PAP CPU Usage Monitoring",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"pap-metrics\"} * 100",
     "legendFormat": "system: {{pod}}"
    },
    {
     "expr": "process_cpu_usage{job=\"pap-metrics\"} * 100",
     "legendFormat": "process: {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"pap-metrics\"}[1h]) * 100",
     "legendFormat": "process_1h: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy PAP Memory Usage Monitoring",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(jvm_memory_used_bytes{area=\"heap\",job=\"pap-metrics\"}) / sum(jvm_memory_max_bytes{area=\"heap\",job=\"pap-metrics\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "100 * sum(jvm_memory_used_bytes{area=\"nonheap\",job=\"pap-metrics\"}) / sum(jvm_memory_max_bytes{area=\"nonheap\",job=\"pap-metrics\"})",
     "legendFormat": "Non Heap"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy PAP JVM Threads",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"pap-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"pap-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"pap-metrics\"}",
     "legendFormat": "Daemon Threads: {{ pod }}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"pap-metrics\"}[1h])",
     "legendFormat": "{{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"pap-metrics\"}[1h])/rate(jvm_gc_pause_seconds_count{job=\"pap-metrics\"}[1h])",
     "legendFormat": "avg {{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "Total number of PAP requests per second filtered by URI and REST method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(method,uri) (rate(http_server_requests_seconds_count{job=\"pap-metrics\"}[5m]))",
     "legendFormat": "{{ method }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Time taken for PAP request filtered by REST method and URI",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method,uri)(http_server_requests_seconds_sum{job=\"pap-metrics\"})/sum by(method,uri)(http_server_requests_seconds_count{job=\"pap-metrics\"})",
     "legendFormat": "{{ method }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "HTTP API Success %age",
   "type": "gauge",
   "description": "Percentage of PAP calls that passed filtered by method and URI",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (method,uri)(http_server_requests_seconds_count{job=\"pap-metrics\",outcome=\"SUCCESS\"})/sum by(method,uri)(http_server_requests_seconds_count{job=\"pap-metrics\"})*100",
     "legendFormat": "{{ method }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "Policy Deployment/Undeployment Stats",
   "type": "bargauge",
   "description": "Stats for Policy PAP Deployment/Undeployment Operations",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"deploy\"})",
     "legendFormat": "Deployment - Total"
    },
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"deploy\",status=\"SUCCESS\"})",
     "legendFormat": "Deployment - Success"
    },
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"deploy\",status=\"FAILURE\"})",
     "legendFormat": "Deployment - Failure"
    },
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"undeploy\"})",
     "legendFormat": "Undeployment - Total"
    },
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"undeploy\",status=\"SUCCESS\"})",
     "legendFormat": "Undeployment - Success"
    },
    {
     "expr": "sum(pap_policy_deployments_total{operation=\"undeploy\",status=\"FAILURE\"})",
     "legendFormat": "Undeployment - Failure"
    }
   ]
  }
 ]
}