{
 "title": "Policy Distribution",
 "description": "Grafana Dashboard for Policy Distribution",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "Uptime for Policy Distribution application",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-process_start_time_seconds{job=\"distribution-metrics\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy Distribution CPU Usage Monitoring",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"distribution-metrics\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy Distribution Memory Usage Monitoring",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by(job)(jvm_memory_bytes_used{area=\"heap\", job=\"distribution-metrics\"}) / sum by(job)(jvm_memory_bytes_max{area=\"heap\", job=\"distribution-metrics\"})",
     "legendFormat": "Heap : {{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy Distribution CPU Usage Monitoring",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(process_cpu_seconds_total{job=\"distribution-metrics\"}[1m]) * 100",
     "legendFormat": "system: {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_seconds_total{job=\"distribution-metrics\"}[5m]) * 100",
     "legendFormat": "process: {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_seconds_total{job=\"distribution-metrics\"}[1h]) * 100",
     "legendFormat": "process_1h: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy Distribution Memory Usage Monitoring",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(jvm_memory_bytes_used{area=\"heap\", job=\"distribution-metrics\"}) / sum(jvm_memory_bytes_max{area=\"heap\", job=\"distribution-metrics\"})",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy Distribution JVM Threads",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"distribution-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak{job=\"distribution-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_state{job=\"distribution-metrics\"}",
     "legendFormat": "State Threads: {{ pod }}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"distribution-metrics\"}[1h])",
     "legendFormat": "{{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"distribution-metrics\"}[1h])/rate(jvm_gc_collection_seconds_count{job=\"distribution-metrics\"}[1h])",
     "legendFormat": "avg {{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Distribution Statistics",
   "type": "bargauge",
   "description": "Stats for Distribution Statistics Count",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_distribution_received_count{job=\"distribution-metrics\"})",
     "legendFormat": "Total Count"
    },
    {
     "expr": "sum(distribution_success_count{job=\"distribution-metrics\"})",
     "legendFormat": "Success Count"
    },
    {
     "expr": "sum(distribution_failure_count{job=\"distribution-metrics\"})",
     "legendFormat": "Failure Count"
    },
    {
     "expr": "sum(total_download_received_count{job=\"distribution-metrics\"})",
     "legendFormat": "Total Download Count"
    },
    {
     "expr": "sum(download_success_count{job=\"distribution-metrics\"})",
     "legendFormat": "Download Success Count"
    },
    {
     "expr": "sum(download_failure_count{job=\"distribution-metrics\"})",
     "legendFormat": "Download Failure Count"
    }
   ]
  }
 ]
}