{
 "title": "Policy Drools-APPS",
 "description": "Grafana Dashboard for Policy Drools-APPS",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quick Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "description": "Uptime per pod for Policy Drools-APPS application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"drools-apps-metrics\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy Drools-APPS CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"drools-apps-metrics\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy Drools-APPS Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area=\"heap\", job=\"drools-apps-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"drools-apps-metrics\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy Drools-APPS CPU Usage Monitoring",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"drools-apps-metrics\"}[$__range])*100",
     "legendFormat": "system: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy Drools-APPS Memory Usage Monitoring",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"drools-apps-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"drools-apps-metrics\"}",
     "legendFormat": "Heap : {{ pod }}"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy Drools-APPS JVM Threads",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"drools-apps-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak{job=\"drools-apps-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_daemon{job=\"drools-apps-metrics\"}",
     "legendFormat": "Daemon Threads: {{ pod }}"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"drools-apps-metrics\"}[$__range])",
     "legendFormat": "{{ gc }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"drools-apps-metrics\"}[$__range])/rate(jvm_gc_collection_seconds_count{job=\"drools-apps-metrics\"}[$__range])",
     "legendFormat": "avg {{ gc }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Deployments Total",
   "type": "bargauge",
   "description": "Policy Deployments Total for Drools-APPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-apps-metrics\", operation=\"deploy\", status=\"SUCCESS\"})",
     "legendFormat": "Deploy - Success"
    },
    {
     "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-apps-metrics\", operation=\"deploy\", status=\"FAILURE\"})",
     "legendFormat": "Deploy - Failure"
    },
    {
     "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-apps-metrics\", operation=\"undeploy\", status=\"SUCCESS\"})",
     "legendFormat": "Undeploy - Success"
    },
    {
     "expr": "avg by(job)(pdpd_policy_deployments_total{job=\"drools-apps-metrics\", operation=\"undeploy\", status=\"FAILURE\"})",
     "legendFormat": "Undeploy - Failure"
    }
   ]
  },
  {
   "title": "Policy Executions",
   "type": "bargauge",
   "description": "Policy Executions Total for Drools-APPS per instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpd_policy_executions_latency_seconds_count{job=\"drools-apps-metrics\", status=\"SUCCESS\"}",
     "legendFormat": "Executions - Count"
    },
    {
     "expr": "irate(pdpd_policy_executions_latency_seconds_sum{job=\"drools-apps-metrics\", status=\"SUCCESS\"}[$__range])",
     "legendFormat": "Executions - Latency (success)"
    },
    {
     "expr": "irate(pdpd_policy_executions_latency_seconds_sum{job=\"drools-apps-metrics\", status=\"FAIL\"}[$__range])",
     "legendFormat": "Executions - Latency (fail)"
    }
   ]
  }
 ]
}