{
 "title": "Policy API Jakarta",
 "description": "Grafana Dashboard for Policy API",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime (days)",
   "type": "stat",
   "description": "Uptime per pod for Policy API application calculated in days",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"api-metrics\"} * 86400",
     "legendFormat": "process_uptime:{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy API CPU Usage Monitoring",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"api-metrics\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy API Memory Usage Monitoring",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * sum by(job)(jvm_memory_used_bytes{area=\"heap\",job=\"api-metrics\"}) / sum by(job)(jvm_memory_max_bytes{area=\"heap\",job=\"api-metrics\"})",
     "legendFormat": "Heap : {{pod}}"
    },
    {
     "expr": "100 * sum by(job)(jvm_memory_used_bytes{area=\"nonheap\",job=\"api-metrics\"}) / sum by(job)(jvm_memory_max_bytes{area=\"nonheap\",job=\"api-metrics\"})",
     "legendFormat": "Non Heap : {{pod}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy API CPU Usage Monitoring",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"api-metrics\"} * 100",
     "legendFormat": "system: {{pod}}"
    },
    {
     "expr": "process_cpu_usage{job=\"api-metrics\"} * 100",
     "legendFormat": "process: {{pod}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{job=\"api-metrics\"}[1h]) * 100",
     "legendFormat": "process_1h: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy API Memory Usage Monitoring",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(jvm_memory_used_bytes{area=\"heap\",job=\"api-metrics\"}) / sum(jvm_memory_max_bytes{area=\"heap\",job=\"api-metrics\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "100 * sum(jvm_memory_used_bytes{area=\"nonheap\",job=\"api-metrics\"}) / sum(jvm_memory_max_bytes{area=\"nonheap\",job=\"api-metrics\"})",
     "legendFormat": "Non Heap"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy API JVM Threads",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"api-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"api-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"api-metrics\"}",
     "legendFormat": "Daemon Threads: {{ pod }}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"api-metrics\"}[1h])",
     "legendFormat": "{{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"api-metrics\"}[1h])/rate(jvm_gc_pause_seconds_count{job=\"api-metrics\"}[1h])",
     "legendFormat": "avg {{action}} ({{cause}}) : {{ pod }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "description": "HTTP API requests rate filtered by URI and REST method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg by(method,uri) (rate(http_server_requests_seconds_count{job=\"api-metrics\"}[5m]))",
     "legendFormat": "{{ method }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Time taken for an API request filtered by REST method and URI",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (method,uri)(http_server_requests_seconds_sum{job=\"api-metrics\"})/sum by(method,uri)(http_server_requests_seconds_count{job=\"api-metrics\"})",
     "legendFormat": "{{ method }} - {{ uri }}"
    }
   ]
  },
  {
   "title": "Policy API Requests",
   "type": "bargauge",
   "description": "Stats for Policy API Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy - Failed"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy - Failed"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy - Failed"
    }
   ]
  },
  {
   "title": "Policy Types API Requests",
   "type": "bargauge",
   "description": "Stats for Policy Types API operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy Type - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy Type - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"POST\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Create Policy Type - Failed"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy Type - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy Type - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"DELETE\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Delete Policy Type - Failed"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy Type - Total"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",outcome=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy Type - Successful"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"api-metrics\",method=\"GET\",outcome!=\"SUCCESS\",uri=~\"/metrics\"})",
     "legendFormat": "Get Policy Type - Failed"
    }
   ]
  }
 ]
}