{
 "title": "Policy APEX-PDP Jakarta",
 "description": "Grafana Dashboard for Policy APEX-PDP",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Quick Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime (days)",
   "type": "stat",
   "description": "Uptime per pod for Policy APEX-PDP application calculated in days",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"apex-pdp-metrics\"}) / 86400",
     "legendFormat": "process_uptime: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Policy APEX-PDP CPU Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"apex-pdp-metrics\"}[5m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Policy APEX-PDP Memory Usage Monitoring",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"apex-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"apex-pdp-metrics\"}",
     "legendFormat": "Heap : {{ pod }}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Policy APEX-PDP CPU Usage Monitoring",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"apex-pdp-metrics\"}[5m])*100",
     "legendFormat": "system: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Policy APEX-PDP Memory Usage Monitoring",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * jvm_memory_bytes_used{area=\"heap\", job=\"apex-pdp-metrics\"} / jvm_memory_bytes_max{area=\"heap\", job=\"apex-pdp-metrics\"}",
     "legendFormat": "Heap : {{ pod }}"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "description": "Policy APEX-PDP JVM Threads",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"apex-pdp-metrics\"}",
     "legendFormat": "Live Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_peak{job=\"apex-pdp-metrics\"}",
     "legendFormat": "Peak Threads: {{ pod }}"
    },
    {
     "expr": "jvm_threads_daemon{job=\"apex-pdp-metrics\"}",
     "legendFormat": "Daemon Threads: {{ pod }}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Collection",
   "type": "timeseries",
   "description": "GC operations per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"apex-pdp-metrics\"}[5m])",
     "legendFormat": "{{ gc }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "description": "Average GC Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"apex-pdp-metrics\"}[5m])/rate(jvm_gc_collection_seconds_count{job=\"apex-pdp-metrics\"}[5m])",
     "legendFormat": "avg {{ gc }} : {{ pod }}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Policy Deployments Total",
   "type": "bargauge",
   "description": "Policy Deployments Total for APEX-PDP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"deploy\", status=\"SUCCESS\"})",
     "legendFormat": "Deploy - Success"
    },
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"deploy\", status=\"FAIL\"})",
     "legendFormat": "Deploy - Failure"
    },
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"deploy\", status=\"TOTAL\"})",
     "legendFormat": "Deploy - Total"
    },
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"undeploy\", status=\"SUCCESS\"})",
     "legendFormat": "Undeploy - Success"
    },
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"undeploy\", status=\"FAIL\"})",
     "legendFormat": "Undeploy - Failure"
    },
    {
     "expr": "avg by(service)(pdpa_policy_deployments_total{job=\"apex-pdp-metrics\", operation=\"undeploy\", status=\"TOTAL\"})",
     "legendFormat": "Undeploy - Total"
    }
   ]
  },
  {
   "title": "Policy Executions Total",
   "type": "bargauge",
   "description": "Policy Executions Total for APEX-PDP per instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\", status=\"SUCCESS\"}",
     "legendFormat": "Executions - SUCCESS : {{ pod }}"
    },
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\", status=\"FAIL\"}",
     "legendFormat": "Executions - FAILURE : {{ pod }}"
    },
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\", status=\"TOTAL\"}",
     "legendFormat": "Executions - TOTAL :  {{ pod }}"
    }
   ]
  },
  { "title": "Engine Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Engine States",
   "type": "piechart",
   "description": "Policy Engine States for APEX-PDP per engine per instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpa_engine_state{job=\"apex-pdp-metrics\"}",
     "legendFormat": "{{ engine_instance_id }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Engine Uptime (days)",
   "type": "stat",
   "description": "Uptime per engine for Policy APEX-PDP application calculated in days",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(engine_instance_id)((time() - pdpa_engine_last_start_timestamp_epoch{job=\"apex-pdp-metrics\"}/1000)/86400)",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  },
  {
   "title": "Engine Executions",
   "type": "timeseries",
   "description": "Number of APEX event execution counter per engine thread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (engine_instance_id)(rate(pdpa_engine_event_executions{job=\"apex-pdp-metrics\"}[5m]))",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  },
  {
   "title": "Engine Average Latency",
   "type": "timeseries",
   "description": "Average time taken to execute an APEX policy in seconds per engine instance per pod",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pdpa_engine_average_execution_time_seconds{job=\"apex-pdp-metrics\"}",
     "legendFormat": "{{ engine_instance_id }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "Engine Latency distribution",
   "type": "heatmap",
   "description": "Time taken to execute the last APEX policy in seconds expressed as a histogram over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by(le)(increase(pdpa_engine_last_execution_time_bucket{job=\"apex-pdp-metrics\"}[$__interval]))",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}