{
 "title": "SLA's Metrics",
 "description": "Dashboard for Service Level Agreeements",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Basic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"}*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(system_load_average_1m{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"})",
     "legendFormat": "Load Average [1m] "
    },
    {
     "expr": "avg(system_cpu_count{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"})",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(system_cpu_usage{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"})",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "avg(process_cpu_usage{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"})",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (id) (jvm_memory_used_bytes{job=~\"api-metrics|acm-metrics|pap-metrics|apex-pdp-metrics\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\".*metrics.*|.*prometheus.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{instance}}{{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{job=~\"api-metrics|acm-metrics|pap-metrics\",outcome=\"SUCCESS\",uri!~\".*metrics.*|.*prometheus.*\"}[5m]) / irate(http_server_requests_seconds_count{job=~\"api-metrics|acm-metrics|pap-metrics\",outcome=\"SUCCESS\",uri!~\".*metrics.*|.*prometheus.*\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{instance}}{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Server Requests Max",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=~\"api-metrics|acm-metrics|pap-metrics\",uri!~\".*metrics.*|.*prometheus.*\"}",
     "legendFormat": "{{method}} [{{status}}] - {{instance}}{{uri}}"
    }
   ]
  },
  { "title": "Deployment statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Successful deployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pap_policy_deployments_total{operation=\"deploy\",status=\"SUCCESS\"}"
    }
   ]
  },
  {
   "title": "Successful undeployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pap_policy_deployments_total{operation=\"undeploy\",status=\"SUCCESS\"}"
    }
   ]
  },
  {
   "title": "Failed deployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pap_policy_deployments_total{operation=\"deploy\",status=\"FAILURE\"}"
    }
   ]
  },
  {
   "title": "Failed undeployments",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pap_policy_deployments_total{operation=\"undeploy\",status=\"FAILURE\"}"
    }
   ]
  },
  {
   "title": "Policy Executions",
   "type": "stat",
   "description": "Policy Executions Total for APEX-PDP",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\",status=\"SUCCESS\"}",
     "legendFormat": "Successful"
    },
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\",status=\"FAIL\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "pdpa_policy_executions_total{job=\"apex-pdp-metrics\",status=\"TOTAL\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Deployment timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(pap_policy_deployments_seconds_sum[5m])/irate(pap_policy_deployments_seconds_count[5m])",
     "legendFormat": "{{operation}} - {{status}}"
    }
   ]
  },
  { "title": "Apex-PDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Engines Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpa_engine_state{job=\"apex-pdp-metrics\"}",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  },
  {
   "title": "Engine Uptime (since last start)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() * 1000) - (pdpa_engine_last_start_timestamp_epoch{job=\"apex-pdp-metrics\"})",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  },
  {
   "title": "Avg Engine Execution Time",
   "type": "timeseries",
   "description": "Number of APEX event execution counter per engine thread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pdpa_engine_average_execution_time_seconds{job=\"apex-pdp-metrics\"}[5m])",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  },
  {
   "title": "Engine Executions Count",
   "type": "piechart",
   "description": "Number of APEX event execution counter per engine thread",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pdpa_engine_event_executions{job=\"apex-pdp-metrics\"}",
     "legendFormat": "{{ engine_instance_id }}"
    }
   ]
  }
 ]
}