#  ============LICENSE_START=======================================================
#   Copyright (C) 2024 Nordix Foundation.
#  ================================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#  ============LICENSE_END=========================================================

spring:
  application:
    name: sim-ppnt
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  security:
    user:
      name: ${RESTSERVER_USER}
      password: ${RESTSERVER_PASSWORD}

security:
  enable-csrf: false

participant:
  intermediaryParameters:
    topics:
      operationTopic: policy-acruntime-participant
      syncTopic: acm-ppnt-sync
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c90
    clampAutomationCompositionTopics:
      topicSources:
        - topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - "{{ .Values.global.kafkaServer }}:9092"
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
          useHttps: false
          allowTracing: {{ include "policy-clamp-ac-sim-ppnt.jaeger-enabled" . }}
          additionalProps:
            group.id: policy-clamp-ac-sim-ppnt
        - topic: ${participant.intermediaryParameters.topics.syncTopic}
          servers:
            - "{{ .Values.global.kafkaServer }}:9092"
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
          useHttps: false
          allowTracing: {{ include "policy-clamp-ac-sim-ppnt.jaeger-enabled" . }}
      topicSinks:
        - topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - "{{ .Values.global.kafkaServer }}:9092"
          topicCommInfrastructure: kafka
          useHttps: false
          allowTracing: {{ include "policy-clamp-ac-sim-ppnt.jaeger-enabled" . }}
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.SimAutomationCompositionElement
        typeVersion: 1.0.0

management:
  tracing:
    propagation:
      produce: [{{ .Values.jaeger.producer.type }}]
    sampling:
      probability: {{ .Values.jaeger.sampling.probability }}
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
server:
  port: 6969
  servlet:
    context-path: /onap/policy/simparticipant
  ssl:
    enabled: false

tracing:
  enabled: {{ .Values.jaeger.enabled }}
  exporter:
    endpoint: "{{ .Values.jaeger.collector.host }}:{{ include "policy-clamp-ac-sim-ppnt.exporter-port" . }}"
    protocol: {{ .Values.jaeger.collector.protocol }}
  sampler:
    jaeger-remote:
      endpoint: "{{ .Values.jaeger.collector.host }}:{{ .Values.jaeger.collector.portJaegerGrpc }}"