spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

security:
  enable-csrf: false
participant:
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: ${participantId:101c62b3-8918-41b9-a747-d21eb79c6c90}
    topics:
      operationTopic: policy-acruntime-participant
      syncTopic: acm-ppnt-sync
    clampAutomationCompositionTopics:
      topicSources:
        - topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
          useHttps: false
          additionalProps:
            group.id: policy-clamp-ac-sim-ppnt
        - topic: ${participant.intermediaryParameters.topics.syncTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
          useHttps: false
      topicSinks:
        - topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: kafka
          useHttps: false
    participantSupportedElementTypes:
      -
        typeName: ${supportedElementTypeName:org.onap.policy.clamp.acm.SimAutomationCompositionElement}
        typeVersion: ${supportedElementTypeVersion:1.0.0}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
server:
  port: 6969
  ssl:
    enabled: false
  servlet:
    context-path: /onap/policy/simparticipant
